fails on adjust customer
note order pkey is mia

BEGIN (implicit)
SELECT "User".name AS "User_name", "User".notes AS "User_notes", "User".client_id AS "User_client_id", "User".id AS "User_id", "User".username AS "User_username", "User".email AS "User_email", "User".password_hash AS "User_password_hash" 
FROM "User" 
WHERE "User".id = ?
[cached since 44.24s ago] ('admin',)
Col ('User_name', 'User_notes', 'User_client_id', 'User_id', 'User_username', 'User_email', 'User_password_hash')
Row ('admin name', None, None, 'admin', None, None, 'p')
BEGIN (implicit)
SELECT "Orders"."OrderID" AS "Orders_OrderID", "Orders"."CustomerID" AS "Orders_CustomerID", "Orders"."OrderDate" AS "Orders_OrderDate", "Orders"."ShipDate" AS "Orders_ShipDate", "Orders"."AmountTotal" AS "Orders_AmountTotal", "Orders"."Notes" AS "Orders_Notes" 
FROM "Orders" 
WHERE "Orders"."OrderID" = ?
 LIMIT ? OFFSET ?
[cached since 42.65s ago] (2, 1, 0)
Col ('Orders_OrderID', 'Orders_CustomerID', 'Orders_OrderDate', 'Orders_ShipDate', 'Orders_AmountTotal', 'Orders_Notes')
Row (2, 2, None, None, Decimal('10.9900000000'), 'hurry')
SELECT "Items"."ItemID" AS "Items_ItemID", "Items"."OrderID" AS "Items_OrderID", "Items"."ProductID" AS "Items_ProductID", "Items"."Quantity" AS "Items_Quantity", "Items"."Amount" AS "Items_Amount", "Items"."UnitPrice" AS "Items_UnitPrice" 
FROM "Items" 
WHERE ? = "Items"."OrderID"
[cached since 42.64s ago] (2,)
Col ('Items_ItemID', 'Items_OrderID', 'Items_ProductID', 'Items_Quantity', 'Items_Amount', 'Items_UnitPrice')
Row (3, 2, 1, 1, Decimal('10.9900000000'), Decimal('10.9900000000'))

Logic Phase:		BEFORE COMMIT(session=0x108c6e5d0)
Logic Phase:		ROW LOGIC(session=0x108c6e5d0) (sqlalchemy before_flush)
..Orders[not available] {Delete - client} OrderID: 2, CustomerID: 2, OrderDate: None, ShipDate: None, AmountTotal: 10.9900000000, Notes: hurry  row: 0x108b08290  session: 0x108c6e5d0  ins_upd_dlt: dlt
SELECT "Customers"."CustomerID" AS "Customers_CustomerID", "Customers"."FirstName" AS "Customers_FirstName", "Customers"."LastName" AS "Customers_LastName", "Customers"."Balance" AS "Customers_Balance", "Customers"."CreditLimit" AS "Customers_CreditLimit" 
FROM "Customers" 
WHERE "Customers"."CustomerID" = ?
[cached since 42.65s ago] (2,)
Col ('Customers_CustomerID', 'Customers_FirstName', 'Customers_LastName', 'Customers_Balance', 'Customers_CreditLimit')
Row (2, 'Jane', 'Smith', Decimal('10.9900000000'), Decimal('3000.0000000000'))
'InstanceState' object has no attribute 'primary_key'
Traceback (most recent call last):
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/safrs/safrs_api.py", line 670, in method_wrapper
    safrs.DB.session.commit()
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/sqlalchemy/orm/scoping.py", line 553, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1906, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1221, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1196, in _prepare_impl
    self.session.flush()
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4154, in flush
    self._flush(objects)
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4183, in _flush
    self.dispatch.before_flush(self, flush_context, objects)
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/sqlalchemy/event/attr.py", line 378, in __call__
    fn(*args, **kw)
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/logic_bank/exec_trans_logic/listeners.py", line 68, in before_flush
    logic_row.delete(reason="client", do_not_adjust_list = do_not_adjust_list)
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/logic_bank/exec_row_logic/logic_row.py", line 989, in delete
    self._adjust_parent_aggregates(do_not_adjust_list=do_not_adjust_list)
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/logic_bank/exec_row_logic/logic_row.py", line 862, in _adjust_parent_aggregates
    each_aggregate.adjust_parent(parent_adjuster, do_not_adjust_list=do_not_adjust_list)
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/logic_bank/rule_type/sum.py", line 56, in adjust_parent
    self.adjust_parent_aggregate(parent_adjustor=parent_adjustor,
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/logic_bank/rule_type/aggregate.py", line 53, in adjust_parent_aggregate
    self.adjust_from_deleted_child(parent_adjustor,
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/logic_bank/rule_type/aggregate.py", line 99, in adjust_from_deleted_child
    is_do_not_adjust = parent_adjustor.parent_logic_row._is_in_list(do_not_adjust_list)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/logic_bank/exec_row_logic/logic_row.py", line 833, in _is_in_list
    pkey_cols = meta.primary_key.columns
                ^^^^^^^^^^^^^^^^
AttributeError: 'InstanceState' object has no attribute 'primary_key'
ROLLBACK
ROLLBACK
Exception on /api/Order/2 [DELETE]
Traceback (most recent call last):
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/flask_restful_swagger_2/__init__.py", line 39, in decorator
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/flask_jwt_extended/view_decorators.py", line 154, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/flask_restful_swagger_2/swagger.py", line 219, in inner
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/safrs/safrs_api.py", line 703, in method_wrapper
    abort(status_code, errors=[errors])
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/flask/helpers.py", line 277, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/Users/val/dev/ApiLogicServer/ApiLogicServer-dev/build_and_test/ApiLogicServer/venv/lib/python3.11/site-packages/werkzeug/exceptions.py", line 861, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
127.0.0.1 - - [28/Sep/2023 10:46:53] "DELETE /api/Order/2 HTTP/1.1" 500 -
